const BUTTONS_ARRAY_EN = [
  [
    { id: 'Backquote', up: '~', down: '`' },
    { id: 'Digit1', up: '!', down: '1' },
    { id: 'Digit2', up: '@', down: '2' },
    { id: 'Digit3', up: '#', down: '3' },
    { id: 'Digit4', up: '$', down: '4' },
    { id: 'Digit5', up: '%', down: '5' },
    { id: 'Digit6', up: '^', down: '6' },
    { id: 'Digit7', up: '&', down: '7' },
    { id: 'Digit8', up: '*', down: '8' },
    { id: 'Digit9', up: '(', down: '9' },
    { id: 'Digit0', up: ')', down: '0' },
    { id: 'Minus', up: '_', down: '-' },
    { id: 'Equal', up: '+', down: '=' },
    { id: 'Backspace', down: 'Backspace' },
  ],
  [
    { id: 'Tab', down: '\t' },
    { id: 'KeyQ', down: 'Q' },
    { id: 'KeyW', down: 'W' },
    { id: 'KeyE', down: 'E' },
    { id: 'KeyR', down: 'R' },
    { id: 'KeyT', down: 'T' },
    { id: 'KeyY', down: 'Y' },
    { id: 'KeyU', down: 'U' },
    { id: 'KeyI', down: 'I' },
    { id: 'KeyO', down: 'O' },
    { id: 'KeyP', down: 'P' },
    { id: 'BracketLeft', down: '[' },
    { id: 'BracketRight', down: ']' },
    { id: 'Backslash', down: '\\' },
    { id: 'Delete', down: 'Del' },
  ],
  [
    { id: 'CapsLock', down: 'CapsLock' },
    { id: 'KeyA', down: 'A' },
    { id: 'KeyS', down: 'S' },
    { id: 'KeyD', down: 'D' },
    { id: 'KeyF', down: 'F' },
    { id: 'KeyG', down: 'H' },
    { id: 'KeyH', down: 'H' },
    { id: 'KeyJ', down: 'J' },
    { id: 'KeyK', down: 'K' },
    { id: 'KeyL', down: 'L' },
    { id: 'Semicolon', down: ';' },
    { id: 'Quote', down: "'" },
    { id: 'Enter', down: '\n' },
  ],
  [
    { id: 'ShiftLeft', down: 'Shift' },
    { id: 'KeyZ', down: 'Z' },
    { id: 'KeyX', down: 'X' },
    { id: 'KeyC', down: 'C' },
    { id: 'KeyV', down: 'V' },
    { id: 'KeyB', down: 'B' },
    { id: 'KeyN', down: 'N' },
    { id: 'KeyM', down: 'M' },
    { id: 'Comma', down: ',' },
    { id: 'Period', down: '.' },
    { id: 'Slash', down: '/' },
    { id: 'ArrowUp', down: '↑' },
    { id: 'ShiftRight', down: 'Shift' },
  ],
  [
    { id: 'ControlLeft', down: 'Ctrl' },
    { id: 'MetaLeft', down: 'Win' },
    { id: 'AltLeft', down: 'Alt' },
    {
      id: 'Space',
      down: '&nbsp',
    },
    { id: 'AltRight', down: 'Alt' },
    { id: 'ControlRight', down: 'Ctrl' },
    { id: 'ArrowLeft', down: '←' },
    { id: 'ArrowDown', down: '↓' },
    { id: 'ArrowRight', down: '→' },
  ],
];

const keyText = [
  'Tab',
  'Backquote',
  'Digit1',
  'Digit2',
  'Digit3',
  'Digit4',
  'Digit5',
  'Digit5',
  'Digit6',
  'Digit7',
  'Digit8',
  'Digit9',
  'Digit0',
  'Minus',
  'Equal',
  'KeyQ',
  'KeyW',
  'KeyE',
  'KeyR',
  'KeyT',
  'KeyY',
  'KeyU',
  'KeyI',
  'KeyO',
  'KeyP',
  'BracketLeft',
  'BracketRight',
  'Backslash',
  'KeyA',
  'KeyS',
  'KeyD',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyJ',
  'KeyK',
  'KeyL',
  'Semicolon',
  'Quote',
  'KeyZ',
  'KeyX',
  'KeyC',
  'KeyV',
  'KeyB',
  'KeyN',
  'KeyM',
  'Comma',
  'Period',
  'Slash',
  'ArrowUp',
  'ArrowLeft',
  'ArrowDown',
  'ArrowRight',
];

const BUTTONS_ARRAY_RU = [
  [
    { id: 'Backquote', up: '~', down: 'Ё' },
    { id: 'Digit1', up: '!', down: '1' },
    { id: 'Digit2', up: '@', down: '2' },
    { id: 'Digit3', up: '#', down: '3' },
    { id: 'Digit4', up: '$', down: '4' },
    { id: 'Digit5', up: '%', down: '5' },
    { id: 'Digit6', up: '^', down: '6' },
    { id: 'Digit7', up: '&', down: '7' },
    { id: 'Digit8', up: '*', down: '8' },
    { id: 'Digit9', up: '(', down: '9' },
    { id: 'Digit0', up: ')', down: '0' },
    { id: 'Minus', up: '_', down: '-' },
    { id: 'Equal', up: '+', down: '=' },
    { id: 'Backspace', down: 'Backspace' },
  ],
  [
    { id: 'Tab', down: '\t' },
    { id: 'KeyQ', down: 'Й' },
    { id: 'KeyW', down: 'Ц' },
    { id: 'KeyE', down: 'У' },
    { id: 'KeyR', down: 'К' },
    { id: 'KeyT', down: 'Е' },
    { id: 'KeyY', down: 'Н' },
    { id: 'KeyU', down: 'Г' },
    { id: 'KeyI', down: 'Ш' },
    { id: 'KeyO', down: 'Щ' },
    { id: 'KeyP', down: 'З' },
    { id: 'BracketLeft', down: 'Х' },
    { id: 'BracketRight', down: 'Ъ' },
    { id: 'Backslash', down: '\\' },
    { id: 'Delete', down: 'Del' },
  ],
  [
    { id: 'CapsLock', down: 'CapsLock' },
    { id: 'KeyA', down: 'Ф' },
    { id: 'KeyS', down: 'Ы' },
    { id: 'KeyD', down: 'В' },
    { id: 'KeyF', down: 'А' },
    { id: 'KeyG', down: 'П' },
    { id: 'KeyH', down: 'Р' },
    { id: 'KeyJ', down: 'О' },
    { id: 'KeyK', down: 'Л' },
    { id: 'KeyL', down: 'Д' },
    { id: 'Semicolon', down: 'Ж' },
    { id: 'Quote', down: 'Э' },
    { id: 'Enter', down: '\n' },
  ],
  [
    { id: 'ShiftLeft', down: 'Shift' },
    { id: 'KeyZ', down: 'Я' },
    { id: 'KeyX', down: 'Ч' },
    { id: 'KeyC', down: 'С' },
    { id: 'KeyV', down: 'М' },
    { id: 'KeyB', down: 'И' },
    { id: 'KeyN', down: 'Т' },
    { id: 'KeyM', down: 'Ь' },
    { id: 'Comma', down: 'Б' },
    { id: 'Period', down: 'Ю' },
    { id: 'Slash', down: '.' },
    { id: 'ArrowUp', down: '↑' },
    { id: 'ShiftRight', down: 'Shift' },
  ],
  [
    { id: 'ControlLeft', down: 'Ctrl' },
    { id: 'MetaLeft', down: 'Win' },
    { id: 'AltLeft', down: 'Alt' },
    {
      id: 'Space',
      down: '&nbsp',
    },
    { id: 'AltRight', down: 'Alt' },
    { id: 'ControlRight', down: 'Ctrl' },
    { id: 'ArrowLeft', down: '←' },
    { id: 'ArrowDown', down: '↓' },
    { id: 'ArrowRight', down: '→' },
  ],
];

export { BUTTONS_ARRAY_EN };
export { keyText };
export { BUTTONS_ARRAY_RU };
