const BUTTONS_ARRAY_EN = [
  [
    { id: 'Backquote', up: '~', down: '`' },
    { id: 'Digit1', up: '!', down: '1' },
    { id: 'Digit2', up: '@', down: '2' },
    { id: 'Digit3', up: '#', down: '3' },
    { id: 'Digit4', up: '$', down: '4' },
    { id: 'Digit5', up: '%', down: '5' },
    { id: 'Digit6', up: '^', down: '6' },
    { id: 'Digit7', up: '&', down: '7' },
    { id: 'Digit8', up: '*', down: '8' },
    { id: 'Digit9', up: '(', down: '9' },
    { id: 'Digit0', up: ')', down: '0' },
    { id: 'Minus', up: '_', down: '-' },
    { id: 'Equal', up: '+', down: '=' },
    { id: 'Backspace', down: 'Backspace' },
  ],
  [
    { id: 'Tab', down: 'Tab' },
    { id: 'KeyQ', down: 'Q' },
    { id: 'KeyW', down: 'W' },
    { id: 'KeyE', down: 'E' },
    { id: 'KeyR', down: 'R' },
    { id: 'KeyT', down: 'T' },
    { id: 'KeyY', down: 'Y' },
    { id: 'KeyU', down: 'U' },
    { id: 'KeyI', down: 'I' },
    { id: 'KeyO', down: 'O' },
    { id: 'KeyP', down: 'P' },
    { id: 'BracketLeft', down: '[' },
    { id: 'BracketRight', down: ']' },
    { id: 'Backslash', down: '\\' },
  ],
  [
    { id: 'CapsLock', down: 'CapsLock' },
    { id: 'KeyA', down: 'A' },
    { id: 'KeyS', down: 'S' },
    { id: 'KeyD', down: 'D' },
    { id: 'KeyF', down: 'F' },
    { id: 'KeyG', down: 'H' },
    { id: 'KeyH', down: 'H' },
    { id: 'KeyJ', down: 'J' },
    { id: 'KeyK', down: 'K' },
    { id: 'KeyL', down: 'L' },
    { id: 'Semicolon', down: ';' },
    { id: 'Quote', down: "'" },
    { id: 'Enter', down: 'Enter' },
  ],
  [
    { id: 'ShiftLeft', down: 'Shift' },
    { id: 'KeyZ', down: 'Z' },
    { id: 'KeyX', down: 'X' },
    { id: 'KeyC', down: 'C' },
    { id: 'KeyV', down: 'V' },
    { id: 'KeyB', down: 'B' },
    { id: 'KeN', down: 'N' },
    { id: 'KeM', down: 'M' },
    { id: 'Comma', down: ',' },
    { id: 'Period', down: '.' },
    { id: 'Slash', down: '/' },
    { id: 'ArrowUp', down: '↑' },
    { id: 'ShiftRight', down: 'Shift' },
  ],
  [
    { id: 'ControlLeft', down: 'Ctrl' },
    { id: 'MetaLeft', down: 'Win' },
    { id: 'AltLeft', down: 'Alt' },
    {
      id: 'Space',
      down: '',
    },
    { id: 'AltRight', down: 'Alt' },
    { id: 'MetaLeft', down: 'Win' },
    { id: 'ControlRight', down: 'Ctrl' },
    { id: 'ArrowLeft', down: '←' },
    { id: 'ArrowDown', down: '↓' },
    { id: 'ArrowRight', down: '→' },
  ],
];

export { BUTTONS_ARRAY_EN };
